name: CD

on:
  push:
    branches: [master]

jobs:
  #  build:
  #    runs-on: ubuntu-latest
  #    steps:
  #      - uses: actions/checkout@v2
  #      - uses: actions/setup-node@v1
  #        with:
  #          node-version: 12
  #      - run: yarn
  #      - run: yarn test
  #
  #  publish-npm:
  #    needs: build
  #    runs-on: ubuntu-latest
  #    steps:
  #      - uses: actions/checkout@v2
  #      - uses: actions/setup-node@v1
  #        with:
  #          node-version: 12
  #          registry-url: https://registry.npmjs.org/
  #      - run: yarn
  #      - run: yarn semantic-release
  #        env:
  #          NPM_TOKEN: ${{secrets.NPM_TOKEN}}
  #          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
  #          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
  #          CI: true

  publish-storybook:
    #    needs: publish-npm
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: |
          yarn
          yarn build-storybook
          git config --global user.email "${{github.actor}}@users.noreply.github.com"
          git config --global user.name "${{github.actor}} (via CD)"
          git add .
          git commit --no-verify -m "chore(storybook): rebuild documentation site"
          git push -f https://${{github.actor}}:${{secrets.GITHUB_TOKEN}}@github.com/${{github.repository}}.git HEAD:${{ github.ref }}
