name: Pull Request

on:
  pull_request:
    branches: [master, beta]
    types: [opened, synchronize, reopened]

jobs:
  test:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout ${{github.ref}} from zachpwr/blazon-ui.git'
        uses: actions/checkout@v2

      - name: Read .nvmrc
        run: echo "##[set-output name=NVMRC;]$(cat .nvmrc)"
        id: nvmrc

      - name: 'Install Node v${{steps.nvmrc.outputs.NVMRC}}'
        uses: actions/setup-node@v1
        with:
          node-version: '${{steps.nvmrc.outputs.NVMRC}}'

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Initialize Yarn cache
        uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install Node Dependencies
        run: yarn install --frozen-lockfile --check-files

      - name: Run Unit Tests
        run: yarn test
